name: Build (GCC 16)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/mattkretz/cplusplus-ci/gcc16

    steps:
      - uses: actions/checkout@v4

      - name: Set PATH for cmake-latest
        run: echo /opt/cmake-latest/bin >> $GITHUB_PATH

      - name: Configure CMake
        shell: bash
        run: cmake -S . -B build

      - name: Build
        shell: bash
        run: cmake --build build --parallel

      - name: Run 
        shell: bash
        run: cmake --build . --target run
